create table t_ss_forma_de_pagamento (
  cd_cartao number generated by default as identity,
  nr_cvv varchar2(3),
  nm_cartao varchar2(50),
  nr_cartao varchar2(20),
  dt_vencimento date not null,
  cd_plano number,
  primary key (cd_cartao)
);

create table t_ss_perguntas (
  cd_pergunta number generated by default as identity,
  ds_pergunta varchar2(2049) not null,
  primary key (cd_pergunta)
);

create table t_ss_plano (
  cd_plano number generated by default as identity,
  vl_plano_anual number(38,2),
  vl_plano_mensal number(38,2),
  ds_plano varchar2(255) not null,
  primary key (cd_plano)
);

create table t_ss_resposta (
  cd_resposta number generated by default as identity,
  ds_resposta varchar2(2049) not null,
  cd_pergunta number,
  primary key (cd_resposta)
);

create table t_ss_usuario (
  cd_usuario number generated by default as identity,
  dt_nascimento date not null,
  ds_email varchar2(255),
  nm_usuario varchar2(50),
  ds_senha varchar2(255),
  nr_telefone varchar2(255),
  cd_plano number,
  primary key (cd_usuario)
);

create table t_ss_usuario_perguntas (
    cd_usuario number,
    cd_pergunta number,
    primary key (cd_usuario, cd_pergunta)
);
CREATE TABLE T_SS_USUARIO_PERGUNTAS (
  CD_USUARIO NUMBER,
  CD_PERGUNTA NUMBER,
  PRIMARY KEY (CD_USUARIO, CD_PERGUNTA)
);


alter table t_ss_forma_de_pagamento
add constraint FKdegs3nq8itt6rp4lw3jkxk1eq
foreign key (cd_plano) references t_ss_plano;

alter table t_ss_resposta
add constraint FKef0vnr8cyaj0be3ayh2p8q1rt
foreign key (cd_pergunta) references t_ss_perguntas;

alter table t_ss_usuario
add constraint FK6fp4pvl8xq70b1f8a2vrji524
foreign key (cd_plano) references t_ss_plano;

alter table t_ss_usuario_perguntas
add constraint FKstw5cg6ho0os9720w05f892vk
foreign key (cd_usuario) references t_ss_usuario;

alter table t_ss_usuario_perguntas
add constraint FKgjxk5vxxpmr18y1ehv4ye59bg
foreign key (cd_pergunta) references t_ss_perguntas;
